[versions]
guava = "33.5.0-android" # https://github.com/google/guava/releases
kamel = "1.0.8" # https://github.com/Kamel-Media/Kamel/releases
ktor = "3.3.3" # https://github.com/ktorio/ktor/releases
moko-mvvm = "0.16.1" # https://github.com/icerockdev/moko-mvvm/releases
moko-resource = "0.25.2" # https://github.com/icerockdev/moko-resources
napier = "2.7.1" # https://github.com/AAkira/Napier
navigation = "0.10.0" # https://github.com/chRyNaN/navigation/tree/develop
play-services-cast-framework = "22.2.0" # https://mvnrepository.com/artifact/com.google.android.gms/play-services-cast-framework?repo=google
xmlutil = "0.91.3" # https://github.com/pdvrieze/xmlutil/releases
google-services = "4.4.4" # https://maven.google.com/web/index.html?q=com.google.gms.google-services#com.google.gms.google-services:com.google.gms.google-services.gradle.plugin
firebase = "34.7.0" # https://maven.google.com/web/index.html?q=firebase-bom#com.google.firebase:firebase-bom
crashlytics = "3.0.6" # https://maven.google.com/web/index.html?q=crashly#com.google.firebase.crashlytics:com.google.firebase.crashlytics.gradle.plugin

#kotlin dependencies
kotlinx-datetime = "0.7.1"# https://github.com/Kotlin/kotlinx-datetime/releases
kotlinx-serialization-json = "1.9.0"# https://github.com/Kotlin/kotlinx.serialization/releases
kotlinx-coroutines-guava = "1.10.2"# https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-guava/
kotlinx-coroutines = "1.10.2"# https://github.com/Kotlin/kotlinx.coroutines

# compose stack:
compose-multiplatform = "1.9.3" # https://github.com/JetBrains/compose-multiplatform/releases
compose-compiler = "1.5.15" # https://developer.android.com/jetpack/androidx/releases/compose-compiler

# other androidx dependencies
activity-compose = "1.12.2"# https://developer.android.com/jetpack/androidx/releases/activity
concurrent-futures = "1.3.0"# https://developer.android.com/jetpack/androidx/releases/concurrent
core-ktx = "1.17.0"# https://developer.android.com/jetpack/androidx/releases/core
lifecycle = "2.10.0"# https://developer.android.com/jetpack/androidx/releases/lifecycle
compose-material3 = "1.10.0"# https://mvnrepository.com/artifact/androidx.compose.ui/ui-tooling?repo=google
media3 = "1.9.0"# https://developer.android.com/jetpack/androidx/releases/media3

# core dependencies
kotlin = "2.3.0" # https://github.com/JetBrains/kotlin/releases
android-gradle-plugin = "8.13.2" # https://developer.android.com/studio/releases/gradle-plugin
junit = "4.13.2"# depend on intellij

[libraries]
# single line library
napier = { module = "io.github.aakira:napier", version.ref = "napier" }
kamel = { module = "media.kamel:kamel-image", version.ref = "kamel" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit = { module = "junit:junit", version.ref = "junit" }
play-services-cast-framework = { module = "com.google.android.gms:play-services-cast-framework", version.ref = "play-services-cast-framework" }
kotlinx-coroutines-guava = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-guava", version.ref = "kotlinx-coroutines-guava" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
concurrent-futures = { module = "androidx.concurrent:concurrent-futures", version.ref = "concurrent-futures" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }

# moko resource
moko-resources_generator = { module = "dev.icerock.moko:resources-generator", version.ref = "moko-resource" }
moko-resources_compose = { module = "dev.icerock.moko:resources-compose", version.ref = "moko-resource" }
moko-resources = { module = "dev.icerock.moko:resources", version.ref = "moko-resource" }
moko-resources-test = { module = "dev.icerock.moko:resources-test", version.ref = "moko-resource" }

# moko mvvm
mvvm-compose = { module = "dev.icerock.moko:mvvm-compose", version.ref = "moko-mvvm" }
mvvm-flow_compose = { module = "dev.icerock.moko:mvvm-flow-compose", version.ref = "moko-mvvm" }
mvvm-livedata_compose = { module = "dev.icerock.moko:mvvm-livedata-compose", version.ref = "moko-mvvm" }
mvvm-core = { module = "dev.icerock.moko:mvvm-core", version.ref = "moko-mvvm" }
mvvm-livedata = { module = "dev.icerock.moko:mvvm-livedata", version.ref = "moko-mvvm" }
mvvm-state = { module = "dev.icerock.moko:mvvm-state", version.ref = "moko-mvvm" }

# ktor
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-json = { module = "io.ktor:ktor-client-json", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }

# navigation
navigation = { module = "com.chrynan.navigation:navigation-compose", version.ref = "navigation" }

# xml util
xmlutil-core = { module = "io.github.pdvrieze.xmlutil:core", version.ref = "xmlutil" }
xmlutil-serialization = { module = "io.github.pdvrieze.xmlutil:serialization", version.ref = "xmlutil" }

# kotlinx
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }

# androidx media3
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3-exoplayer_hls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "media3" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
media3-cast = { module = "androidx.media3:media3-cast", version.ref = "media3" }
media3-session = { module = "androidx.media3:media3-session", version.ref = "media3" }


# androidx lifecycle
lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "lifecycle" }



# androidx compose
material3-core = { module = "androidx.compose.material3:material3-core", version.ref = "compose-material3" }
material3-window-size = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "compose-material3" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose-material3" }
compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose-material3" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-material3" }
compose-ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding", version.ref = "compose-material3" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose-material3" }
compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose-material3" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-material3" }
compose-ui-tooling_preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-material3" }

#firebase android
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx", version = "22.5.0" }
firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx", version = "19.4.4" }

[bundles]
moko-mvvm = ["mvvm-compose", "mvvm-flow-compose", "mvvm-livedata-compose", "mvvm-core", "mvvm-livedata", "mvvm-state"]
ktor-common = ["ktor-client-core", "ktor-client-json", "ktor-client-logging"]
xmlutil = ["xmlutil-core", "xmlutil-serialization"]
media3 = ["media3-exoplayer", "media3-exoplayer-hls", "media3-ui", "media3-cast", "media3-session"]
compose = ["compose-runtime", "compose-runtime-livedata", "compose-ui", "compose-ui-viewbinding", "compose-ui-tooling-preview",
    "compose-foundation", "compose-foundation-layout", "compose-ui-tooling"]


[plugins]
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
com-android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
com-android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
org-jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
